-- Add separate columns for user and AI tags if they don't exist
ALTER TABLE public.videos
ADD COLUMN IF NOT EXISTS user_tags text[] DEFAULT '{}',
ADD COLUMN IF NOT EXISTS ai_tags text[] DEFAULT '{}';

-- Add comments for clarity
COMMENT ON COLUMN public.videos.user_tags IS 'Tags added by the user';
COMMENT ON COLUMN public.videos.ai_tags IS 'Tags generated by AI';
COMMENT ON COLUMN public.videos.tags IS 'Combined tags (user + AI) for display';

-- Create a function to merge tags automatically
CREATE OR REPLACE FUNCTION public.merge_video_tags()
RETURNS TRIGGER AS $$
BEGIN
  -- Merge user_tags and ai_tags into tags column
  NEW.tags := array_cat(
    COALESCE(NEW.user_tags, '{}'),
    COALESCE(NEW.ai_tags, '{}')
  );
  -- Remove duplicates
  NEW.tags := ARRAY(SELECT DISTINCT unnest(NEW.tags));
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger to automatically update tags when user_tags or ai_tags change
DROP TRIGGER IF EXISTS merge_tags_trigger ON public.videos;
CREATE TRIGGER merge_tags_trigger
BEFORE INSERT OR UPDATE OF user_tags, ai_tags ON public.videos
FOR EACH ROW
EXECUTE FUNCTION public.merge_video_tags();