-- Migration to switch from Cloudinary to Bunny.net Stream
-- Run this in your Supabase SQL Editor

-- Rename cloudinary_url to bunny_thumbnail_url
ALTER TABLE videos 
RENAME COLUMN cloudinary_url TO bunny_thumbnail_url;

-- Add Bunny.net specific columns
ALTER TABLE videos
ADD COLUMN IF NOT EXISTS bunny_video_id TEXT,
ADD COLUMN IF NOT EXISTS bunny_video_url TEXT;

-- Update comments
COMMENT ON COLUMN videos.bunny_thumbnail_url IS 'URL to the video thumbnail generated by Bunny.net';
COMMENT ON COLUMN videos.bunny_video_id IS 'Unique video ID in Bunny.net Stream';
COMMENT ON COLUMN videos.bunny_video_url IS 'URL to the video file in Bunny.net CDN';

-- Verify the changes
SELECT 
    column_name, 
    data_type, 
    is_nullable,
    column_default
FROM information_schema.columns 
WHERE table_schema = 'public' 
AND table_name = 'videos' 
AND column_name IN ('bunny_thumbnail_url', 'bunny_video_id', 'bunny_video_url', 'thumb_status', 'thumb_error_message')
ORDER BY ordinal_position;